# SPDX-License-Identifier: AGPL-3.0-or-later
# Pin the Rust toolchain for reproducible builds across all contributors.

[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
