[alias]
# Requires cargo-llvm-cov (https://github.com/taiki-e/cargo-llvm-cov) and
# `rustup component add llvm-tools-preview`.
coverage = "llvm-cov --workspace --ignore-filename-regex tests/ --fail-under-lines 90"
