// SPDX-License-Identifier: AGPL-3.0-or-later

//! Deploy profile generation from graph + launch profiles + tolerances.
//!
//! Merges the graph's per-node data with primalSpring's centralized
//! knowledge (port defaults, env var names, launch profiles) into
//! actionable deploy profiles that downstream tooling can consume
//! instead of hardcoding operational knowledge.

use std::collections::HashMap;

use super::DeployGraph;
use crate::launcher::{LaunchProfile, load_launch_profiles};
use crate::{env_keys, tolerances};

/// Actionable deploy profile for a single primal node.
///
/// Generated by [`deploy_profiles`] from a graph's node data merged
/// with launch profiles and tolerances. Downstream deploy tooling
/// (scripts, biomeOS, projectNUCLEUS) can consume this instead of
/// maintaining parallel hardcoded knowledge.
#[derive(Debug, Clone)]
pub struct PrimalDeployProfile {
    /// Primal name (e.g. `"beardog"`).
    pub name: String,
    /// Binary name to invoke.
    pub binary: String,
    /// Full CLI args including subcommand (e.g. `["server", "--socket", "..."]`).
    pub args: Vec<String>,
    /// Environment variables to set on the child process.
    pub env: HashMap<String, String>,
    /// Tier 5 TCP fallback port (from tolerances), if known for this primal.
    ///
    /// Valid for containers, architectures without UDS, and standalone
    /// compositions. Higher tiers (Songbird, UDS, registry) are preferred
    /// when available — see the discovery escalation hierarchy.
    pub port: Option<u16>,
    /// Health check method (JSON-RPC method name).
    pub health_method: String,
    /// Security model for this node (e.g. `"btsp"`, `"tower_delegated"`).
    pub security_model: String,
    /// Nodes that must be healthy before this one starts.
    pub depends_on: Vec<String>,
    /// Whether this node is required for the composition.
    pub required: bool,
    /// Whether this node should be spawned (vs. external/pre-existing).
    pub spawn: bool,
    /// Capability routing key, if declared.
    pub by_capability: Option<String>,
    /// Preferred discovery tier from the graph's transport metadata.
    ///
    /// `None` means "use the full escalation hierarchy."
    /// Values like `"uds_only"`, `"songbird"`, or `"tcp"` hint at the
    /// deployment's intended transport.
    pub discovery_tier: Option<String>,
}

/// Map primal names to their tier 5 TCP fallback ports from tolerances.
///
/// Port assignments confirmed against ironGate live deployment (2026-05-04).
fn tcp_fallback_port(name: &str) -> Option<u16> {
    match name {
        "beardog" => Some(tolerances::TCP_FALLBACK_BEARDOG_PORT),
        "songbird" => Some(tolerances::TCP_FALLBACK_SONGBIRD_PORT),
        "squirrel" => Some(tolerances::TCP_FALLBACK_SQUIRREL_PORT),
        "toadstool" => Some(tolerances::TCP_FALLBACK_TOADSTOOL_PORT),
        "nestgate" => Some(tolerances::TCP_FALLBACK_NESTGATE_PORT),
        "rhizocrypt" => Some(tolerances::TCP_FALLBACK_RHIZOCRYPT_PORT),
        "loamspine" => Some(tolerances::TCP_FALLBACK_LOAMSPINE_PORT),
        "coralreef" => Some(tolerances::TCP_FALLBACK_CORALREEF_PORT),
        "barracuda" => Some(tolerances::TCP_FALLBACK_BARRACUDA_PORT),
        "skunkbat" => Some(tolerances::TCP_FALLBACK_SKUNKBAT_PORT),
        "biomeos" => Some(tolerances::TCP_FALLBACK_BIOMEOS_PORT),
        "sweetgrass" => Some(tolerances::TCP_FALLBACK_SWEETGRASS_PORT),
        "petaltongue" => Some(tolerances::TCP_FALLBACK_PETALTONGUE_PORT),
        _ => None,
    }
}

/// Map primal names to the env var name for their TCP port override.
fn port_env_key(name: &str) -> Option<&'static str> {
    match name {
        "beardog" => Some(env_keys::BEARDOG_PORT),
        "songbird" => Some(env_keys::SONGBIRD_PORT),
        "squirrel" => Some(env_keys::SQUIRREL_PORT),
        "toadstool" => Some(env_keys::TOADSTOOL_PORT),
        "nestgate" => Some(env_keys::NESTGATE_PORT),
        "rhizocrypt" => Some(env_keys::RHIZOCRYPT_PORT),
        "loamspine" => Some(env_keys::LOAMSPINE_PORT),
        "coralreef" => Some(env_keys::CORALREEF_PORT),
        "barracuda" => Some(env_keys::BARRACUDA_PORT),
        "skunkbat" => Some(env_keys::SKUNKBAT_PORT),
        "biomeos" => Some(env_keys::BIOMEOS_PORT),
        "sweetgrass" => Some(env_keys::SWEETGRASS_PORT),
        "petaltongue" => Some(env_keys::PETALTONGUE_PORT),
        _ => None,
    }
}

/// Merge a graph node with its launch profile.
fn merge_profile_env(
    name: &str,
    profile: &LaunchProfile,
    defaults: &LaunchProfile,
) -> HashMap<String, String> {
    let mut env = HashMap::new();

    for (k, v) in &defaults.extra_env {
        env.insert(k.clone(), v.clone());
    }
    for (k, v) in &profile.extra_env {
        env.insert(k.clone(), v.clone());
    }

    if let Some(port_key) = port_env_key(name) {
        if let Some(port) = tcp_fallback_port(name) {
            env.entry(port_key.to_owned())
                .or_insert_with(|| port.to_string());
        }
    }

    env
}

/// Build CLI args from graph node args + launch profile.
fn build_args(node_args: &[String], profile: &LaunchProfile, defaults: &LaunchProfile) -> Vec<String> {
    let mut args = Vec::new();

    let subcommand = profile
        .subcommand
        .as_deref()
        .or(defaults.subcommand.as_deref())
        .unwrap_or("server");
    if !subcommand.is_empty() {
        args.push(subcommand.to_owned());
    }

    for arg in node_args {
        if !args.contains(arg) {
            args.push(arg.clone());
        }
    }

    for arg in &profile.extra_args {
        if !args.contains(arg) {
            args.push(arg.clone());
        }
    }

    args
}

/// Generate deploy profiles for all spawnable nodes in a graph.
///
/// Merges each node's graph-declared data with:
/// - Launch profiles from `config/primal_launch_profiles.toml`
/// - TCP fallback ports from `tolerances`
/// - Environment variable names from `env_keys`
///
/// Returns profiles in graph startup order (sorted by `order`).
/// Only includes nodes where `spawn = true`.
#[must_use]
pub fn deploy_profiles(graph: &DeployGraph) -> Vec<PrimalDeployProfile> {
    let (defaults, profiles) = load_launch_profiles().unwrap_or_default();

    let empty_profile = LaunchProfile::default();

    graph
        .graph
        .node
        .iter()
        .filter(|n| n.spawn)
        .map(|node| {
            let profile = profiles.get(&node.name).unwrap_or(&empty_profile);
            let security = node
                .security_model
                .as_deref()
                .or(profile.security_model.as_deref())
                .or(defaults.security_model.as_deref())
                .unwrap_or("btsp");

            let discovery_tier = graph
                .graph
                .metadata
                .as_ref()
                .and_then(|m| m.transport.clone());

            PrimalDeployProfile {
                name: node.name.clone(),
                binary: node.binary.clone(),
                args: build_args(&node.args, profile, &defaults),
                env: merge_profile_env(&node.name, profile, &defaults),
                port: tcp_fallback_port(&node.name),
                health_method: node.health_method.clone(),
                security_model: security.to_owned(),
                depends_on: node.depends_on.clone(),
                required: node.required,
                spawn: node.spawn,
                by_capability: node.by_capability.clone(),
                discovery_tier,
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deploy::load_graph;
    use std::path::Path;

    fn graphs_path(name: &str) -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("../graphs/{name}"))
    }

    #[test]
    fn deploy_profiles_nucleus_complete() {
        let graph = load_graph(&graphs_path("nucleus_complete.toml")).unwrap();
        let profiles = deploy_profiles(&graph);

        assert!(!profiles.is_empty());

        let beardog = profiles.iter().find(|p| p.name == "beardog").unwrap();
        assert_eq!(beardog.port, Some(tolerances::TCP_FALLBACK_BEARDOG_PORT));
        assert_eq!(beardog.security_model, "btsp");
        assert_eq!(beardog.health_method, "health.liveness");
        assert!(beardog.required);

        let songbird = profiles.iter().find(|p| p.name == "songbird").unwrap();
        assert_eq!(songbird.port, Some(tolerances::TCP_FALLBACK_SONGBIRD_PORT));
        assert!(!songbird.depends_on.is_empty());
    }

    #[test]
    fn deploy_profiles_preserves_node_args() {
        let graph = load_graph(&graphs_path("nucleus_complete.toml")).unwrap();
        let profiles = deploy_profiles(&graph);

        let petaltongue = profiles.iter().find(|p| p.name == "petaltongue");
        if let Some(pt) = petaltongue {
            assert!(pt.args.contains(&"server".to_owned()));
        }
    }

    #[test]
    fn deploy_profiles_respects_spawn_false() {
        let graph = load_graph(&graphs_path("nucleus_complete.toml")).unwrap();
        let profiles = deploy_profiles(&graph);

        assert!(
            profiles.iter().all(|p| p.spawn),
            "all profiles should have spawn=true (non-spawn nodes filtered)"
        );
        assert!(
            !profiles.iter().any(|p| p.name == "biomeos_neural_api"),
            "biomeos_neural_api has spawn=false and should be excluded"
        );
    }

    #[test]
    fn deploy_profiles_tower_graph() {
        let graph = load_graph(&graphs_path("profiles/tower.toml")).unwrap();
        let profiles = deploy_profiles(&graph);

        assert!(profiles.len() >= 2);
        assert!(profiles.iter().any(|p| p.name == "beardog"));
        assert!(profiles.iter().any(|p| p.name == "songbird"));
    }
}
